apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: restapi
  name: restapi-nodeport
  namespace: restapi
  
spec:
  
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: restapi
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
